// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PairProgrammingApi.DataAccess;

#nullable disable

namespace PairProgrammingApi.Migrations
{
    [DbContext(typeof(PairContext))]
    [Migration("20241201195336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PairProgrammingApi.Modules.HealthCheck.Models.HealthCheckDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CheckSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("check_successful");

                    b.Property<string>("CreatedContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_context");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("LastUpdateContext")
                        .HasColumnType("text")
                        .HasColumnName("last_update_context");

                    b.Property<DateTimeOffset?>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_health_checks");

                    b.ToTable("health_checks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
